### ISSUE TITLE
Atomic int support

### ISSUE THREAD

**Issue by xlab** [PathDNA/atoms#4]
Using atomic's Uintptr methods maybe?

**Comment by itsmontoya** [comment]
So you want Int and Uint support?

**Comment by xlab** [comment]
Yes, this should give the ability to store `int` and `uint` atomically.

Something like that:

```go
type intAtomic struct {
	v uintptr
}

func (i *intAtomic) Update(newVal int) (oldVal int) {
	old := atomic.SwapUintptr(&i.v, uintptr(newVal))
	return int(old)
}

func (i *intAtomic) Read() int {
	return int(atomic.LoadUintptr(&i.v))
}
```

**Comment by itsmontoya** [comment]
Alright

**Comment by itsmontoya** [comment]
PR opened here: https://github.com/Path94/atoms/pull/5

@xlab can you take a look at the int implementation and let me know if you're happy with it? If so, I can move forward on the uint implementation. Just a note, I wanted to approach this without using unsafe.

**Comment by xlab** [comment]
`int` is not always `int64`

Also, the approach presented above doesn't use unsafe.

**Comment by itsmontoya** [comment]
Check out the most up to date version, https://github.com/Path94/atoms/pull/5

**Comment by xlab** [comment]
<3

**Comment by itsmontoya** [comment]
This has been implemented and integrated. Cheers!
